# 최초 인증서 발급 시에만 사용하는 임시 설정 (init-https.sh 내부에서 자동 사용)
events {}

http {
    server {
        listen 80;
        server_name locker-cse.sch.ac.kr;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 200 "OK";
        }
    }
}
